# Selection Colors
selection_foreground     #ffffff
selection_background     #cc0000

# Window border Colors
active_border_color      #ee0000
inactive_border_color    #4a4a4a

# Kitty tabs colors 
active_tab_foreground    #ffffff
active_tab_background    #cc0000
inactive_tab_foreground  #d0d0d0
inactive_tab_background  #2b2b2b

# Basic color
background               #111111
foreground               #f5f5f5

# 16 main colors
color0                   #1f1f1f
color1                   #cc0000
color2                   #5f875f
color3                   #d7af5f
color4                   #5f87af
color5                   #875f87
color6                   #5f8787
color7                   #d0d0d0
color8                   #5c5c5c
color9                   #ee0000
color10                  #87af87
color11                  #ffd75f
color12                  #87afd7
color13                  #af87af
color14                  #87afaf
color15                  #ffffff

# Cursor colors
cursor                   #ee0000
cursor_text_color        #ffffff

# Url color
url_color                #ee0000
